# Generated by Django 4.0.1 on 2022-01-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('juridico', 'Jurídico'), ('fisico', 'Físico'), ('especial', 'Especial')], max_length=128),
        ),
    ]
