# Generated by Django 4.0.1 on 2022-01-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('juridico', 'Jurídico'), ('fisico', 'Físico'), ('especial', 'Especial')], max_length=28),
        ),
        migrations.DeleteModel(
            name='Ponto',
        ),
    ]
