# Generated by Django 4.0.1 on 2022-01-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_endereco_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='cliente',
            new_name='cliente_id',
        ),
    ]
