# Generated by Django 4.0.1 on 2022-01-11 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0003_rename_cliente_endereco_cliente_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='cliente_id',
        ),
    ]
