# Generated by Django 4.0.1 on 2022-01-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0002_contratos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contratos',
        ),
    ]
